### 파이썬에서 데이터 분석을 하기 위한 필수 Library
#### (1) Pandas
- 2008년 금융데이터 분석용으로 출발
- 통계와 데이터 과학(Data Science), 머신러닝에도 사용 
#### (2) Numpy
- 파이썬 기반 수치해석(Numerical Method)
- 선형대수(Linear Algebra)연산에 필요한 다차원 배열과 배열연산을 수행하는 함수 제공 
#### (3) Matplotlib
- 그래픽이나 차트등 그래픽으로 표현하는 파이썬 시각화 도구 
#### (4) sckit-learn
- 머신러닝 학습을 위한 파이썬 라이브러리     
-----    
Pandas/Numpy는 고급 데이터 분석과 수치계산등의 기능을 제공하는 확장 모듈       
Numpy는 수치계산을 효율적으로 하기 위한 모듈로 다차원 배열과 고수준의 수학 함수를 제공      
Pandas는 테이블 분석 기능을 제공하는 라이브러리로 CSV, XLSX등의 데이터를 읽고 원하는 형식으로 변환 가능     
-----
#### DataFrame    
- Pandas에서 사용하는 기본 데이터 타입
- 데이터프레임을 정의할때는 2차원 리스트를 전달 받는다.

------
#### Pandas를 이용하여 DataFrame 만들기

In [3]:
import pandas as pd

In [7]:
# 행방향으로 DataFrame 만들기 : List
# List로 Data 정의
list01 = [
	[10, 20, 30],
	[40, 50, 60],
	[70, 80, 90]
]

# DataFrame 변환
df = pd.DataFrame(list01)
df

    0   1   2
0  10  20  30
1  40  50  60
2  70  80  90

In [9]:
# List Type으로 Dataset을 정의하여 DataFrame 생성

df = \
	pd.DataFrame(
		[
			[10, 20, 30],
			[40, 50, 60],
			[70, 80, 90]
		]
	)
df

    0   1   2
0  10  20  30
1  40  50  60
2  70  80  90

> DataFrame은 index(rows)와 columns로 구성되어 있음.

In [13]:
# Column이름이 Pandas의 기본 이름이므로 Column 이름 변경

df.columns = ['A', 'B', 'C']
df

    A   B   C
0  10  20  30
1  40  50  60
2  70  80  90

#### DataFrame에서 값 추출하기

In [18]:
# 열 기준으로 추출하기 : A번 열의 데이터 추출하기
df.loc[:,'A']

0    10
1    40
2    70
Name: A, dtype: int64

In [ ]:
# 열 기준으로 추출 : A,B번 열 데이터 추출
df.loc[:,['A','B']] # Column 이름으로 추출 
df.loc[:,'A':'B']  # Column의 범위로 추출 
df.loc[:,:'B'] # Column의 처음부터 시작하여 범위로 추출

    A   B
0  10  20
1  40  50
2  70  80

In [24]:
# 범위를 정해 행 기준으로 추출하기 
df.loc[0,:]

A    10
B    20
C    30
Name: 0, dtype: int64

In [27]:
# 범위를 정해 행기준으로 추출하기
df.loc[:1,:]
df.loc[[0,1],:]

    A   B   C
0  10  20  30
1  40  50  60

In [30]:
# 행과 열의 이름으로 데이터 추출
print(df.loc[1,'B'])

50

In [36]:
# DataFrame의 컬럼 이름과 index이름 출력하기
print(df.columns)
print(list(df.index))

Index(['A', 'B', 'C'], dtype='object')
[0, 1, 2]

----
#### Series
- Pandas에서 사용하는 기본 데이터 
- 1차원 리스트로 전달
- index는 자동 생성

In [39]:
list01 = [10, 20, 30]
s1 = pd.Series(list01)
print(s1)
print(s1[1])

0    10
1    20
2    30
dtype: int64
20

> Series는 List 대비 index이름이 정해지고 보여진다.

----
#### Dictionary({K:V})로 DataFrame 만들기

In [43]:
dic01 = {
	"weight" : [ 80, 70.4, 65.5, 45.9, 51.2],
	"height" : [170,  180,  155,  143, 154],
	'type'   : ['f',  'n',  'n',  't', 't']
}

tbl = pd.DataFrame(dic01)
tbl

   weight  height type
0    80.0     170    f
1    70.4     180    n
2    65.5     155    n
3    45.9     143    t
4    51.2     154    t

> dictionay의 key가 dataframe의 컬럼 이름으로 생성된다.

In [50]:
# weight열만 추출하기
tbl.loc[:,'weight']

0    80.0
1    70.4
2    65.5
3    45.9
4    51.2
Name: weight, dtype: float64