#### List를 이용한 DataFrame 생성

In [1]:
import pandas as pd

In [2]:
# List로 Data 정의
data = [
	[15, '남', '덕영중'],
	[17, '여', '수리중']
]
data

[[15, '남', '덕영중'], [17, '여', '수리중']]

In [3]:
df = \
	pd.DataFrame(
		data,
		index=['준서',"예은"],
		columns=['나이','성별','학교']
	)
df

    나이 성별   학교
준서  15  남  덕영중
예은  17  여  수리중

In [4]:
# 나이 항목만 추출 : Index를 정의하여 이름이 보인다. 
df.loc[:,'나이']

준서    15
예은    17
Name: 나이, dtype: int64

In [5]:
# 준서의 나이만 추출하기
print(df.loc['준서','나이'])

15

In [6]:
# 예은의 나이, 학교를 추출
df.loc['예은',['나이','학교']]

나이     17
학교    수리중
Name: 예은, dtype: object

---
#### 행과 열이름 변경하기

In [7]:
# 행과 열이름 확인
print(df.index)
print(df.columns)

Index(['준서', '예은'], dtype='object')
Index(['나이', '성별', '학교'], dtype='object')

In [8]:
# 행이 이름을 학생1, 학생2로 변경하기
df.index = ['학생1', '학생2']
df

     나이 성별   학교
학생1  15  남  덕영중
학생2  17  여  수리중

In [9]:
# 컬럼이름 : 연령, 남녀, 소속 으로 변경하기
df.columns = ['연령', '남녀', '소속']
df

     연령 남녀   소속
학생1  15  남  덕영중
학생2  17  여  수리중

#### 원하는 부분만 변경하기

In [10]:
# 연령 -> 나이 
df.rename(
	columns={
		'연령':'나이'
	},
	inplace=True
)

df

     나이 남녀   소속
학생1  15  남  덕영중
학생2  17  여  수리중

In [11]:
# rename 1번으로 남녀 -> 성별, 소속 -> 학교로 변경하기
df.rename(
	columns={
		'남녀':'성별',
		'소속':'학교'
	},
	inplace=True
)

df

     나이 성별   학교
학생1  15  남  덕영중
학생2  17  여  수리중

In [12]:
# 행이름 변경하기 :학생1 -> 준서, 학생2:예은 
df.rename(
	index={
		'학생1':'준서',
		'학생2':'예은'
	},
	inplace=True
)
df

    나이 성별   학교
준서  15  남  덕영중
예은  17  여  수리중

In [13]:
# Ex : 나이 -> 연령, 예은 -> 학생2 

df.rename(
	columns={
		'나이':'연령'
	},
	index={
		'예은':'학생2'
	},
	inplace=True
)

df

     연령 성별   학교
준서   15  남  덕영중
학생2  17  여  수리중

---
#### 행삭제

In [14]:
exam_data = {
	'수학' : [90, 80, 70],
	'영어' : [98, 89, 95],
	'음악' : [85, 95, 100],
	'체육' : [100, 90, 90],
}
exam_data

{'수학': [90, 80, 70],
 '영어': [98, 89, 95],
 '음악': [85, 95, 100],
 '체육': [100, 90, 90]}

In [15]:
# DataFrame 생성하기
df = \
	pd.DataFrame(
		exam_data
	)
df

   수학  영어   음악   체육
0  90  98   85  100
1  80  89   95   90
2  70  95  100   90

In [16]:
# Index 생성
df.index = ['서준','우현','인아']
df

    수학  영어   음악   체육
서준  90  98   85  100
우현  80  89   95   90
인아  70  95  100   90

In [17]:
# DataFrame 복사하기
df2 = df.copy()
df2

    수학  영어   음악   체육
서준  90  98   85  100
우현  80  89   95   90
인아  70  95  100   90

In [18]:
# index가 우현인 행을 삭제 
df2.drop(
	'우현',
	axis = 'rows', # axis = 0
	inplace=True
)
df2

    수학  영어   음악   체육
서준  90  98   85  100
인아  70  95  100   90

In [19]:
df2.shape

(2, 4)

In [20]:
df3 = df.copy()
df3

    수학  영어   음악   체육
서준  90  98   85  100
우현  80  89   95   90
인아  70  95  100   90

In [21]:
# index가 우현, 인아를 동시에 삭제
df3.drop(
	['우현','인아'],
	axis='rows',
	inplace=True
)
df3

    수학  영어  음악   체육
서준  90  98  85  100

---
#### 열삭제

In [22]:
df4 = df.copy()
df4

    수학  영어   음악   체육
서준  90  98   85  100
우현  80  89   95   90
인아  70  95  100   90

In [23]:
# 수학 컬럼 삭제
df4.drop(
	'수학',
	axis='columns', # axis = 1
	inplace=True
)
df4

    영어   음악   체육
서준  98   85  100
우현  89   95   90
인아  95  100   90

In [24]:
# df4에서 영어, 음악 컬럼 삭제
df4.drop(
	['영어','음악'],
	axis='columns',
	inplace=True
)
df4

     체육
서준  100
우현   90
인아   90

In [25]:
df5 = df.copy()
df5

    수학  영어   음악   체육
서준  90  98   85  100
우현  80  89   95   90
인아  70  95  100   90

In [26]:
# df5에서 영어, 체육, 음악을 삭제 

df5.loc[:,['수학']]

    수학
서준  90
우현  80
인아  70

---
#### 데이터 추출하기 위한 선택
- loc : index나 columns의 이름을 기준으로 선택 
- iloc : 정수형 index를 기준으로 선택

In [27]:
df

    수학  영어   음악   체육
서준  90  98   85  100
우현  80  89   95   90
인아  70  95  100   90

In [28]:
# index가 서준인 행을 추출
df.loc['서준',:]
df.iloc[0,:]

수학     90
영어     98
음악     85
체육    100
Name: 서준, dtype: int64

In [29]:
# 서준과 우현의 정보를 추출
df.loc[['서준','우현'],:] # indexing
df.loc['서준':'우현',:] # Slicing

df.iloc[[0,1],:] # indexing
df.iloc[0:1+1,:] # Slicing

    수학  영어  음악   체육
서준  90  98  85  100
우현  80  89  95   90

#### Slicing의 step 사용
iloc[start:stop+1:step, start:stop+1:step]

In [30]:
# 행은 모두 추출하고 열은 0, 2번으로 추출(단, Slicing만 사용가능)

df.iloc[:,::2]

    수학   음악
서준  90   85
우현  80   95
인아  70  100

---
#### 행과 열을 이용한 Data 선택

In [32]:
exam_data = {
    '이름' : ['서준','우현','인아'],
    '수학' : [90, 80, 70],
    '영어' : [98, 89, 95],
    '음악' : [85, 95, 100],
    '체육' : [100, 90, 90]
}
exam_data

{'이름': ['서준', '우현', '인아'],
 '수학': [90, 80, 70],
 '영어': [98, 89, 95],
 '음악': [85, 95, 100],
 '체육': [100, 90, 90]}

In [33]:
df2 = pd.DataFrame(exam_data)
df2

   이름  수학  영어   음악   체육
0  서준  90  98   85  100
1  우현  80  89   95   90
2  인아  70  95  100   90

In [34]:
# 이름 컬럼을 index로 정의
df2.set_index('이름', inplace=True)
df2

    수학  영어   음악   체육
이름
서준  90  98   85  100
우현  80  89   95   90
인아  70  95  100   90

In [36]:
# index를 원위치
df2.reset_index(inplace=True)
df2

   이름  수학  영어   음악   체육
0  서준  90  98   85  100
1  우현  80  89   95   90
2  인아  70  95  100   90

In [38]:
df.index.name = '이름'
df

    수학  영어   음악   체육
이름
서준  90  98   85  100
우현  80  89   95   90
인아  70  95  100   90

In [39]:
df.reset_index(inplace=True)
df

   이름  수학  영어   음악   체육
0  서준  90  98   85  100
1  우현  80  89   95   90
2  인아  70  95  100   90

---
열 추가

In [49]:
# df에 국어라는 열을 추가하고 데이터는 80이라고 동일하게 넣자 
'국어' in df.columns

df.loc[:,'국어'] = 80
df['국어2'] = [50, 60, 70] # 여러개의 데이터를 넣을 경우 갯수를 맞추어야 한다.

df

   이름  수학  영어   음악   체육  국어  국어2
0  서준  90  98   85  100  80   50
1  우현  80  89   95   90  80   60
2  인아  70  95  100   90  80   70

---
#### 행 추가

In [52]:
df.loc[3] = 0 
df.loc[4] = ['동규', 90, 80, 70, 60, 50, 40]
df.loc['행5'] = df.loc[3]
df

    이름  수학  영어   음악   체육  국어  국어2
0   서준  90  98   85  100  80   50
1   우현  80  89   95   90  80   60
2   인아  70  95  100   90  80   70
3    0   0   0    0    0   0    0
4   동규  90  80   70   60  50   40
행5   0   0   0    0    0   0    0

In [53]:
# 이름 컬럼을 index로 정의하자
df.set_index('이름', inplace=True)
df

    수학  영어   음악   체육  국어  국어2
이름
서준  90  98   85  100  80   50
우현  80  89   95   90  80   60
인아  70  95  100   90  80   70
0    0   0    0    0   0    0
동규  90  80   70   60  50   40
0    0   0    0    0   0    0

> Index에 동일한 값이 있어도 Index번호는 틀리기 때문에 아무 영향이 없다.

In [57]:
df.loc[0,:]
df.iloc[3]

수학     0
영어     0
음악     0
체육     0
국어     0
국어2    0
Name: 0, dtype: int64