In [2]:
import pandas as pd

In [ ]:
# index로 정할 column이름을 알고 있는 경우 
train = pd.read_csv("../Data/train.csv", index_col="PassengerId")
train.head()

,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
PassengerId,,,,,,,,,,,
1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [7]:
# 데이터를 불러와서 index를 정하는 경우
train = pd.read_csv("../Data/train.csv")
train.set_index("PassengerId", inplace=True)
train.head()

,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
PassengerId,,,,,,,,,,,
1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [8]:
train.tail()

,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
PassengerId,,,,,,,,,,,
887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.00,NaN,S
888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.00,B42,S
889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.45,NaN,S
890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.00,C148,C
891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.75,NaN,Q

In [9]:
# 전체 외형 크기 
train.shape

(891, 11)

In [10]:
# 내부 구성
train.info()

<class 'pandas.core.frame.DataFrame'>
Index: 891 entries, 1 to 891
Data columns (total 11 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Survived  891 non-null    int64
 1   Pclass    891 non-null    int64
 2   Name      891 non-null    object
 3   Sex       891 non-null    object
 4   Age       714 non-null    float64
 5   SibSp     891 non-null    int64
 6   Parch     891 non-null    int64
 7   Ticket    891 non-null    object
 8   Fare      891 non-null    float64
 9   Cabin     204 non-null    object
 10  Embarked  889 non-null    object
dtypes: float64(2), int64(4), object(5)
memory usage: 83.5+ KB

In [20]:
# Survived(0,1), Pclass (1,2,3), Sex(female, male), Embarked(C,S,Q)
print(f"Survived : \t {train.Survived.unique()}")
print(f"Pclass : \t {train.Pclass.unique()}")
print(f"Sex : \t\t {train.Sex.unique()}")
print(f"Embarked : \t {train.Embarked.unique()}")

Survived : 	 [0 1]
Pclass : 	 [3 1 2]
Sex : 		 ['male' 'female']
Embarked : 	 ['S' 'C' 'Q' nan]

In [22]:
# Survived에서 생존수와 사망수를 확인 -> 빈도수
a = train.Survived.value_counts()
a.index = ['사망','생존']
a

사망    549
생존    342
Name: count, dtype: int64

In [23]:
# 객실별(Pcalss) 빈도수 확인
train.Pclass.value_counts()

Pclass
3    491
1    216
2    184
Name: count, dtype: int64

In [31]:
# Sex, Pclass, Survived의 데이터 1~5개 보기 
train[['Sex','Pclass','Survived']].head()
train.loc[:5,['Sex','Pclass','Survived']]

col = ['Sex','Pclass','Survived']
train[col].head()
train.loc[:5,col]

                Sex  Pclass  Survived
PassengerId
1              male       3         0
2            female       1         1
3            female       3         1
4            female       1         1
5              male       3         0

In [33]:
# train의 PassengerId가 1,2,3 추출하기
train.loc[1:3,:]

,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
PassengerId,,,,,,,,,,,
1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S

In [34]:
# train의 PassengerId가 1, 3, 7, 13만 추출하기
train.loc[[1,3,7,13]]

,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
PassengerId,,,,,,,,,,,
1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
13,0,3,"Saundercock, Mr. William Henry",male,20.0,0,0,A/5. 2151,8.0500,NaN,S

In [35]:
# train의 PassengerId가 1, 3, 7, 13의 Pclass, Sex, Survived만 추출하기
train.loc[[1,3,7,13],['Pclass', 'Sex', 'Survived']]

             Pclass     Sex  Survived
PassengerId
1                 3    male         0
3                 3  female         1
7                 1    male         0
13                3    male         0

----
#### Boolean Indexing

In [ ]:
# 타이타닉호에 승선한 남성 인원수는?
print(len(train[train.Sex == 'male']))
print(train[train.Sex == 'male'].shape[0])
print(train[train.Sex == 'male'].Survived.count()) # 결측치는 계산이 않됨

577
577
577

In [51]:
# 운임(Fare)이 20달러 이상을 지불한 사람의 수?
train[train.Fare >= 20].shape[0]

376

In [ ]:
# 운임(Fare)이 평균 운임 이상으로 지급한 사람의 수?
train[train.Fare >= train.Fare.mean()].shape[0]

211

In [59]:
# 운임(Fare)이 평균 운임이상으로 지급한 사람들 중 1등급 객실을 사용한 인원수?
# &(and), |(or), !(not)
train[(train.Fare >= train.Fare.mean()) & (train.Pclass == 1)].shape[0]

159

In [61]:
# 최대 운임을 지불한 사람들은?
train[train.Fare == train.Fare.max()]

,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
PassengerId,,,,,,,,,,,
259,1,1,"Ward, Miss. Anna",female,35.0,0,0,PC 17755,512.3292,NaN,C
680,1,1,"Cardeza, Mr. Thomas Drake Martinez",male,36.0,0,1,PC 17755,512.3292,B51 B53 B55,C
738,1,1,"Lesurer, Mr. Gustave J",male,35.0,0,0,PC 17755,512.3292,B101,C

In [ ]:
# 항구 (Embarked)
# C항구에서 탑승한 인원수
print(f"C항구 탑승인원수 : {train[train.Embarked == 'C'].shape[0]}")
# S항구에서 탑승한 인원수
print(f"S항구 탑승인원수 : {train[train.Embarked == 'S'].shape[0]}")
# Q항구에서 탑승한 인원수
print(f"Q항구 탑승인원수 : {train[train.Embarked == 'Q'].shape[0]}")

C항구 탑승인원수 : 168
S항구 탑승인원수 : 644
Q항구 탑승인원수 : 77

In [69]:
for emb in ['C', 'S', 'Q']:
    print(f"{emb}항구 탑승인원수 : {train[train.Embarked == emb].shape[0]}")

C항구 탑승인원수 : 168
S항구 탑승인원수 : 644
Q항구 탑승인원수 : 77

In [87]:
for emb in train.Embarked.unique():
    print(f"{emb}항구 탑승인원수 : {train[train.Embarked == emb].shape[0]}")

S항구 탑승인원수 : 644
C항구 탑승인원수 : 168
Q항구 탑승인원수 : 77
nan항구 탑승인원수 : 0

In [88]:
# 항구별 탑승 인원수 (NaN도 포함)
for emb, count in train.Embarked.value_counts(dropna=False).items():
    port = "항구 미상(NaN)" if pd.isna(emb) else f"{emb}항구"
    print(f"{port} 탑승인원수 : {count}")

S항구 탑승인원수 : 644
C항구 탑승인원수 : 168
Q항구 탑승인원수 : 77
항구 미상(NaN) 탑승인원수 : 2